services:
  - type: web
    name: partage-backend
    runtime: docker
    rootDir: goguma
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /api/captures/test
    envVars:
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
